### ISSUE TITLE
Open in github command sometimes throws "TypeError: Cannot read properties of undefined (reading 'url')"

### ISSUE THREAD

**Issue by dvdplm** [ziyasal/vscode-open-in-github#174]
Full error message:

```
2024-12-06 11:50:50.709 [error] TypeError: Cannot read properties of undefined (reading 'url')
	at /Users/aggron/.vscode-insiders/extensions/ziyasal.vscode-open-in-github-1.3.6/src/extension.js:44:67
	at /Users/aggron/.vscode-insiders/extensions/ziyasal.vscode-open-in-github-1.3.6/node_modules/git-rev-2/index.js:9:5
	at ChildProcess.exithandler (node:child_process:415:7)
	at ChildProcess.emit (node:events:518:28)
	at maybeClose (node:internal/child_process:1104:16)
	at ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

This happens *sometimes* and seems to depend on which repo I'm working with.

**Comment by dmill** [comment]
FYI this was happening to me when I switched to a new branch locally and hadn't set a remote yet for the branch. Once I pushed the new branch to github the error was resolved.

**Comment by aravind-dqi** [comment]
>FYI this was happening to me when I switched to a new branch locally and hadn't set a remote yet for the branch. Once I pushed the new branch to github the error was resolved.

Makes sense as the new branch in local will not have any remote url, but a proper error handling is expected here

**Comment by axiac** [comment]
The error happens because the code expects to find a `remote` property for each branch it finds in the repo configuration file (`.git/config`) but sometimes there are entries that do not have the `remote` property set for some reason.
Normally, a branch has a section in `.git/config` when it tracks a remote branch and in this case it has the `remote` property set.
Recently, VSCode started producing sections for branches in `.git/config` to store the information that it needs and that information does not include `remote`.
