### ISSUE TITLE
Often it doesn't do anything

### ISSUE THREAD

**Issue by dragos** [ziyasal/vscode-open-in-github#50]
Exception from the Developer tools window:

```
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:136 [Extension Host] TypeError: Cannot read property 'url' of undefined
    at /Users/dragos/.vscode/extensions/ziyasal.vscode-open-in-github-1.2.3/src/extension.js:27:51
    at /Users/dragos/.vscode/extensions/ziyasal.vscode-open-in-github-1.2.3/node_modules/parse-git-config/index.js:31:5
    at /Users/dragos/.vscode/extensions/ziyasal.vscode-open-in-github-1.2.3/node_modules/parse-git-config/index.js:49:7
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

Sometimes it picks up the wrong repository, probably based on some other workspace (if I have multiple windows open). Not sure what's going on.

**Comment by sqren** [comment]
I'm seeing the same error. I'm unable to add a breakpoint to the extension source code but the error is happening here:
https://github.com/ziyasal/vscode-open-in-github/blob/2374e4e98103e070fa917240e55877b6aec5ae2e/src/extension.js#L44

It seems like `config[`remote "${remoteName}"`]` is `undefined`.
