### ISSUE TITLE
Cannot read property 'branch "master"' of undefined

### ISSUE THREAD

**Issue by johnathanludwig** [ziyasal/vscode-open-in-github#71]
I'm getting this error in the dev tools. This only seems to occur on my repositories that are git submodules.

```
[ziyasal.vscode-open-in-github] Cannot read property 'branch "master"' of undefined: TypeError: Cannot read property 'branch "master"' of undefined
	at ~/.vscode/extensions/ziyasal.vscode-open-in-github-1.2.8/src/extension.js:38:50
	at ~/.vscode/extensions/ziyasal.vscode-open-in-github-1.2.8/node_modules/git-rev-2/index.js:9:5
	at ChildProcess.exithandler (child_process.js:209:7)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at maybeClose (internal/child_process.js:899:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by johnathanludwig** [comment]
Looks like the recent release 1.2.9 resolved this issue.
