### ISSUE TITLE
Running the contributed command:'extension.openPrGitProvider' failed.

### ISSUE THREAD

**Issue by rmanalan** [ziyasal/vscode-open-in-github#72]
I'm getting this error when I use the "Open Pull Request" command on OSX 10.12.6

**Comment by ziyasal** [comment]
Hi @rmanalan, thank you for reporting this, 'll be checking asap 👍

**Comment by alankyshum** [comment]
# Software Info
| OS | Mac OS X 10.13 |
| VS Code | Version 1.18.0-Insider |


# Error object
```
{
  "exception": null,
  "error": {
    "name": "Error",
    "message": "Running the contributed command:'extension.openPrGitProvider' failed."
  },
  "promise": {
    "_oncancel": null,
    "_nextState": null,
    "_state": {
      "name": "error",
      "done": null,
      "then": null
    },
    "_listeners": null,
    "_value": {
      "name": "Error",
      "message": "Running the contributed command:'extension.openPrGitProvider' failed."
    },
    "_isException": false,
    "_errorId": 163
  },
  "id": 163
}
```

# Stack Trace:
```
workbench.main.js:sourcemap:10 Running the contributed command:'extension.openPrGitProvider' failed.: Error: Running the contributed command:'extension.openPrGitProvider' failed.
	at e.$executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:412410)
	at t.e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:509979)
	at e._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354972)
	at e._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354662)
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:353689
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355608
	at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:85321
	at e.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84604)
	at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:86326)
	at Socket.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:144387)
```

**Comment by jeffochoa** [comment]
I'm having the same issue on Ubuntu (using bitbucket)

**Comment by tomasklingen** [comment]
Same here with git osx bitbucket.

**Comment by andreamaruccia** [comment]
same here on osx using github

**Comment by ziyasal** [comment]
Hi, sorry for the late fix and thank you for your contributions (feedback, reports etc).

**Comment by andreamaruccia** [comment]
Fixed here thank you
